version: '2'
services:
  db:
    image: mysql:5.6
    volumes:
      - ./backend/db/db_data:/var/lib/mysql
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    expose:
      - 80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: p4ssw0rd!


  wordpress:
    depends_on:
      - phpmyadmin
      - db
    image: wordpress:latest
    volumes:
      - ./backend/wordpress/wp-content:/var/www/html/wp-content
      - ./backend/wordpress/.htaccess:/var/www/html/.htaccess
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_CONFIG_EXTRA:
        define('WP_ALLOW_REPAIR', true );
        define('WP_HOME','${WORDPRESS_URL}:${NGINX_EXTERNAL_PORT}');
        define('WP_SITEURL','${WORDPRESS_URL}:${NGINX_EXTERNAL_PORT}');
    expose:
      - 80
      - 443
  
  nginx:
    build: ./backend/nginx
    links:
      - wordpress
      - phpmyadmin
    ports: 
      - ${NGINX_EXTERNAL_PORT}:80
    volumes:
      - "./backend/nginx/nginx.conf:/etc/nginx/nginx.conf"