version: '3'
services:
  db:
    image: ${DB_ENGINE}:${DB_IMAGE_VERSION}
    volumes:
      - ./backend/db/db_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  frontend:
    build: ./frontend
    environment: 
      PORT: 80
      NODE_ENV: ${NODE_ENV}
      API_URL: ${API_URL}
  
  api:
    build: ./backend/api
    links: 
      - wordpress
    volumes:
      - ./backend/api:/usr/src/app
    environment: 
      NODE_ENV: ${NODE_ENV}
      WP_USERNAME: ${WP_USERNAME}
      WP_PASSWORD: ${WP_PASSWORD}

  wordpress:
    depends_on:
      - phpmyadmin
      - db
    restart: on-failure
    image: wordpress:latest
    volumes:
      - ./backend/wordpress/wp-content:/var/www/html/wp-content
      - ./backend/wordpress/.htaccess:/var/www/html/.htaccess
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_CONFIG_EXTRA:
        define('WP_ALLOW_REPAIR', true );
        define('WP_HOME','${WORDPRESS_URL}:${NGINX_EXTERNAL_PORT}');
        define('WP_SITEURL','${WORDPRESS_URL}:${NGINX_EXTERNAL_PORT}');
  
  nginx:
    build: ./backend/nginx
    links:
      - wordpress
      - phpmyadmin
    ports: 
      - ${NGINX_EXTERNAL_PORT}:80
    volumes:
      - "./backend/nginx/nginx.conf:/etc/nginx/nginx.conf"