version: '2'
services:
  db:
    image: mysql:5.6
    restart: unless-stopped
    volumes:
      - ./backend/db/db_data:/var/lib/mysql
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
      MYSQL_DATABASE: wordpress

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: p4ssw0rd!



  wordpress:
    depends_on:
      - phpmyadmin
      - db
    image: wordpress
    restart: unless-stopped
    volumes:
      - ./backend/wordpress/wp-content:/var/www/html/wp-content
      - ./backend/wordpress/.htaccess:/var/www/html/.htaccess
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: p4ssw0rd!
      WORDPRESS_TABLE_PREFIX: ab_
      WORDPRESS_CONFIG_EXTRA:
        define('JWT_AUTH_SECRET_KEY', 'secret');
        define('JWT_AUTH_CORS_ENABLE', true);
        define('WP_ALLOW_REPAIR', true );
    ports:
      - 8000:80 # Expose http and https
      - 8001:443