version: '3'
services:
  mongo:
    image: ${DB_ENGINE}:${DB_IMAGE_VERSION}
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=strapi
    volumes:
      - ./backend/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  strapi:
    image: strapi/strapi
    links:
      - mongo
    environment: 
      - MONGO_INITDB_DATABASE=strapi
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=mongo
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
    volumes: 
      - ./backend/strapi:/usr/src/api/strapi-app

  frontend:
    build: ./frontend
    environment:
      FACEBOOK_APP_ID: ${FACEBOOK_APP_ID} 
      FACEBOOK_APP_SECRET: ${FACEBOOK_APP_SECRET} 
      PORT: 80
      FRONTEND_URL: "${FRONTEND_URL}:${NGINX_EXTERNAL_PORT}"
      SESSION_SECRET: ${SESSION_SECRET}
      NODE_ENV: ${NODE_ENV}
      API_URL: "${API_URL}:${NGINX_EXTERNAL_PORT}"
  
  nginx:
    build: ./backend/nginx
    links:
      - strapi
      - frontend
    ports: 
      - ${NGINX_EXTERNAL_PORT}:80
    volumes:
      - "./backend/nginx/nginx.conf:/etc/nginx/nginx.conf"