version: '2'
services: 
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./backend/db_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: p4ssw0rd!



  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: p4ssw0rd!



  wordpress:
    depends_on:
      - phpmyadmin
    image: wordpress
    restart: always
    volumes:
      - ./backend/wordpress/wp-content:/var/www/html/wp-content
      - ./backend/wordpress/.htaccess:/var/www/html/.htaccess
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: p4ssw0rd!
      WORDPRESS_CONFIG_EXTRA:
        define('JWT_AUTH_SECRET_KEY', 'secret');
        define('JWT_AUTH_CORS_ENABLE', true);
    ports:
      - 8000:80 # Expose http and https
      - 8001:443